### ISSUE TITLE
permanent future vision after installing forseer

### ISSUE THREAD

**Issue by MuXodious** [LelonDelonMelon/foreseer#1]
I built and setup your foreseer software on my brain interface. I'm using a Tetratronic Rippler Mk. 4 before you call trashware. Anyways, after installation I have gained the ability "foresee" but I cannot turn it off when needed. I'm constantly foreseeing in the future. There were no options provided for removal of this software. Please update your git and instructions and end my suffering. I don't want to know the future so much. It's spoiling my own life.

**Comment by LelonDelonMelon** [comment]
I'd suggest coping. Issue closed. >:(
